language: node_js
sudo:            required
os:
  - linux
node_js:
  - "11.12.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
- npm install --depth 0 --silent
- npm run lint
- npm run build
- npm run test:node
- travis_retry npm run test:browser
- npm run test:typings
- npm run test:deps
- npm run test:size
- npm run build:size
